-- ============================================================
-- Migration 027 – Monthly Subscription Payments
-- ============================================================
-- Run this file against the target database (dev or prod) via
-- the RDS Query Editor, psql, or any SQL client.
--
-- What this migration does:
--   1. Adds courses.payment_type  (ONE_TIME | MONTHLY_SUBSCRIPTION)
--      NOTE: price column is reused as the monthly fee when MONTHLY_SUBSCRIPTION
--   2. Adds enrollments.payment_type  (denormalised copy for fast queries)
--   3. Creates monthly_subscription_payments table
--   4. Creates 9 indexes on monthly_subscription_payments
--   5. Creates updated_at trigger on monthly_subscription_payments
--
-- All statements are idempotent (IF NOT EXISTS / IF EXISTS guards).
-- ============================================================

-- ------------------------------------------------------------
-- 1. courses.payment_type
-- ------------------------------------------------------------
ALTER TABLE courses
    ADD COLUMN IF NOT EXISTS payment_type VARCHAR(30) NOT NULL DEFAULT 'ONE_TIME'
        CHECK (payment_type IN ('ONE_TIME', 'MONTHLY_SUBSCRIPTION'));

-- ------------------------------------------------------------
-- 2. enrollments.payment_type  (denormalised from courses for fast queries)
-- ------------------------------------------------------------
ALTER TABLE enrollments
    ADD COLUMN IF NOT EXISTS payment_type VARCHAR(30) NOT NULL DEFAULT 'ONE_TIME'
        CHECK (payment_type IN ('ONE_TIME', 'MONTHLY_SUBSCRIPTION'));

-- ------------------------------------------------------------
-- 4. monthly_subscription_payments table
--    One row per student per billing month for MONTHLY_SUBSCRIPTION courses.
--    Generated by staff via POST /monthly-subscriptions/generate (idempotent).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS monthly_subscription_payments (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    enrollment_id    UUID NOT NULL REFERENCES enrollments(id) ON DELETE CASCADE,
    company_id       UUID NOT NULL REFERENCES companies(id)   ON DELETE CASCADE,
    student_id       UUID NOT NULL REFERENCES students(id)    ON DELETE CASCADE,
    course_id        UUID NOT NULL REFERENCES courses(id)     ON DELETE CASCADE,
    branch_id        UUID NOT NULL REFERENCES branches(id)    ON DELETE CASCADE,
    billing_year     INTEGER NOT NULL,
    billing_month    INTEGER NOT NULL CHECK (billing_month BETWEEN 1 AND 12),
    amount_due       DECIMAL(10, 2) NOT NULL DEFAULT 0,
    amount_paid      DECIMAL(10, 2) NOT NULL DEFAULT 0,
    payment_status   VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                         CHECK (payment_status IN ('PENDING', 'PAID', 'PARTIAL', 'OVERDUE')),
    due_date         DATE NOT NULL,
    paid_date        DATE,
    notes            TEXT,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (enrollment_id, billing_year, billing_month)
);

-- ------------------------------------------------------------
-- 5. Indexes
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_msp_enrollment_id  ON monthly_subscription_payments(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_msp_company_id     ON monthly_subscription_payments(company_id);
CREATE INDEX IF NOT EXISTS idx_msp_student_id     ON monthly_subscription_payments(student_id);
CREATE INDEX IF NOT EXISTS idx_msp_course_id      ON monthly_subscription_payments(course_id);
CREATE INDEX IF NOT EXISTS idx_msp_branch_id      ON monthly_subscription_payments(branch_id);
CREATE INDEX IF NOT EXISTS idx_msp_billing_year   ON monthly_subscription_payments(billing_year);
CREATE INDEX IF NOT EXISTS idx_msp_billing_month  ON monthly_subscription_payments(billing_month);
CREATE INDEX IF NOT EXISTS idx_msp_payment_status ON monthly_subscription_payments(payment_status);
CREATE INDEX IF NOT EXISTS idx_msp_due_date       ON monthly_subscription_payments(due_date);

-- ------------------------------------------------------------
-- 6. updated_at trigger
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS update_monthly_subscription_payments_updated_at
    ON monthly_subscription_payments;

CREATE TRIGGER update_monthly_subscription_payments_updated_at
    BEFORE UPDATE ON monthly_subscription_payments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
